### ISSUE TITLE
VS 2015 can't open can't create the project, 

### ISSUE THREAD

**Issue by jassmith** [xamarin/AndroidSupportComponents#110]
_From @anirugu on May 31, 2018 12:50_

cross post from here https://github.com/conceptdev/xamarin-forms-samples/issues/26

_Copied from original issue: xamarin/Xamarin.Forms#2884_

**Comment by anirugu** [comment]
How to reproduce this bug, here are steps

1. Install Visual Studio 2015 with update 3 (if you install from web, it will be updated to latest patch)

Create the xamarin.forms project, it will work.

2. go to tools > xamarin > update > check now > update to 4.8 something,

now it's broken. The problem was not there when I just using 4.2 but when I update the xamarin to 4.8 it's stopped working.

tested here twice, I hope it will produce same result on other machine too.

**Comment by anirugu** [comment]
For someone who needs a workaround for this, you can downgrade to 4.6 and don't upgrade your NuGet package before making a backup.

This is how I get this problem solved,

**Comment by Redth** [comment]
Is this still an issue? how do we reproduce?
