### ISSUE TITLE
Crash when using SwipeLayout.NestedScrollingEnabled in support 25.3.1

### ISSUE THREAD

**Issue by SamuelDebruyn** [xamarin/AndroidSupportComponents#57]
### Xamarin.Android Version (eg: 6.0):
both 7.3.1.2 and 7.2.0.7

### Operating System & Version (eg: Mac OSX 10.11):
10.12.4

### Support Libraries Version (eg: 23.3.0):
25.3.1

### Describe your Issue:

This exception only occurs on 25.3.1. This does not happen on any other currently released version of the Android support packages. This only happens on Android < 5.0. It seems like the code refers to the implementation in `View` instead of the support version.

Java.Interop.JniEnvironment
no method with name='setNestedScrollingEnabled' signature='(Z)V' in class Landroid/view/View;

```
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()<177beafef290420e9428203111dc0c38>:0
Java.Interop.JniEnvironment.InstanceMethods.GetMethodID(JniObjectReference type, string name, string signature)<539dacac719e4cdf80ab7683d0864862>:0
Java.Interop.JniType.GetInstanceMethod(string name, string signature)<539dacac719e4cdf80ab7683d0864862>:0
Java.Interop.JniPeerMembers.JniInstanceMethods.GetMethodInfo(string encodedMember)<539dacac719e4cdf80ab7683d0864862>:0
Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeVirtualVoidMethod(string encodedMember, IJavaPeerable self, JniArgumentValue* parameters)<539dacac719e4cdf80ab7683d0864862>:0
Android.Views.View.set_NestedScrollingEnabled(bool value)<4a8761a434a5446cbb6d39141be66b72>:0
```

### Steps to Reproduce (with link to sample solution if possible):
1. Create a new `SwipeLayout`
1. Set `NestedScrollingEnabled` to `false` on this layout

**Comment by JonDouglas** [comment]
I'm not sure what `SwipeLayout` refers to here, but the error message is saying that on devices < API 21 it cannot find this method. This is because it was introduced in API 21 and thus requires that API to run the respective code.

https://developer.android.com/reference/android/view/View.html#setNestedScrollingEnabled(boolean)

The case of this exception only occurring on 25.3.1 is interesting, as Google might be calling this method in the support libraries now as they move and change APIs all of the time.

Given you are referring to this library: https://github.com/daimajia/AndroidSwipeLayout

You will want to stay on the same version of support libraries as the library. Given this library is on 25.2.0, we will want to ensure that the binding you are using is also up to date and not on an old version.

https://github.com/daimajia/AndroidSwipeLayout/blob/master/library/build.gradle#L14-L15

**Comment by SamuelDebruyn** [comment]
Hi @JonDouglas,

My apologies for the confusion. I was talking about the [`SwipeRefreshLayout`](https://developer.android.com/reference/android/support/v4/widget/SwipeRefreshLayout.html) in the support packages.

It's correct that the layout was introduced in Android itself in API 21, but the previous versions should be able to use the one in the support packages. That's the one we're using throughout our app.

**Comment by JonDouglas** [comment]
@SamuelDebruyn 

Can you please attach a minimal sample to this issue so it's easier to reproduce this problem? I'd also be curious to see if this happens in Android Studio as well (Which I'll test when I can see it happening in Xamarin.Android)

Thanks!

**Comment by newky2k** [comment]
no response since august
