### ISSUE TITLE
Combine These Support Libs into 1 Nuget Package

### ISSUE THREAD

**Issue by dagostinelli** [xamarin/AndroidSupportComponents#78]
One of the curious choices by the Microsoft teams releasing .NET and other libraries as open source projects has been releasing numerous loose, but tightly coupled Nuget packages.  The libraries from this project specifically are tightly coupled.  For the past several releases, they have been released as a dependent group.

The request of this issue is to combine all of these Nuget packages into a single Nuget package.

It is quite a waste of time to have to worry about all of these loose packages during a Nuget package troubleshooting episode.  While no individual nuget project is a problem, when you consider the other Microsoft projects that participate in the Xamarin ecosystem also releasing a dozen or more dependent and tightly coupled packages, it is a problem.   

Presently, my project has 95 nuget packages when, in reality, I believe I deliberately installed less than 6.  I understand about dependencies, but that's not what we are talking about in this issue.

I must beat this dead horse some more.  When we go to upgrade "Xamarin.Android.Support", it is not 1 package that we are upgrading.  We must upgrade a dozen or so packages.  When in fact, this is ostensibly 1 package, it is wasteful and difficult that it is a dozen.

When there is a problem with the upgrade of some Nuget package (and there often is) it is not as simple as it could be to rollback and try again.   Instead, that kind of operation requires source control support (git/TFS/svn) in order to checkpoint the task before attempting the upgrade and then doing an entire rollack when it fails.  Since so many Microsoft projects are releasing loose nuget packages (which are actually tightly coupled) this process can get extremely complex and error prone.

**Comment by Redth** [comment]
Thanks for the input!  This is definitely a conversation we've had and will continue to revisit.  Originally our intention was to mirror the packages based on how Google separated and released them, and obviously that number has grown substantially over time.

Presumably Google has separated these packages out to allow users to pick and choose only the bits they need.  Google could have of course jammed all of the classes and all of the resources into one single .aar file, but that adds a lot of baggage to the final .apk unless the user has specifically enabled proguard and resource shrinking (which can be problematic at worst, and a bit tricky to configure correctly at best). 

From our perspective, we share the same issues as Google, plus we have the added .NET assembly layer in play.  If we combined everything into one nuget package, we would also need to make sure our .NET assemblies are getting linked in order to keep bloat down (which again can sometimes be messy - though we have a PR exploring adding `[assembly: LinkerSafe]` to our assemblies already).  Plus, we would have to get proguard enabled and ensure unused resources are removed.

So, tl;dr is that this is probably possible and maybe even makes sense to some extent, but it's not without its challenges.

I could see eventually maybe at least grouping some packages (eg: all of the v4 dependencies, and possibly android architecture components), but I doubt we'll ever get to a point where we have 1 single package for Android Support libraries.  If you end up switching to `<PackageReference` in your csproj, it can make your packages list look a bit more sane in the IDE, which might be nice, but of course that doesn't really change what happens under the hood (and can mean other complexities too).

At this point I don't think we'll be able to go this route, and we probably can't until default compilation steps include removing unnecessary resources, running proguard, and linking the support library .NET assemblies.  I do know we are looking at introducing some implicit proguard usage for Xamarin.Android which could facilitate a move to fewer nuget Android Support library packages, so again we will definitely continue to have this conversation.

**Comment by JohannesSchmidt42** [comment]
It would already help if they were combined even without proguard / linker optimizations. 
Since most packages depend on each other there is really no option of picking and choosing. You wan't one? You gotta take most of them anyway. 
If you have (like me) an app that consists of multiple library projects that all need some support library code it gets hard (and slow) to update and babysit hundreds of support library references in a solution. Especially if you switch between branches for parts of the app. 
Also since the support of package references is still buggy we are stuck on packages.config and the not so great fact that each support library package rewrites the csproj file in 3 places when added.   

If all of this could be combined to 1 package a huge pain point would be mended.

**Comment by Redth** [comment]
Well, they don't _all_ depend on each other, so we can't have one big package with everything without some further support for out of the box proguard.  We could probably shove the dependencies of support v4 into a single package again, but I think that's about it.  Yes most apps do use AppCompat V7, but they don't necessarily _have_ to and we can't just force customers only using v4 to opt into shipping appcompat v7.  Same story for Design, and many other libs.

The other problem we face with trying to do this, is we currently don't have a great way to combine multiple .aar files into a single .net .dll assembly (it's structured this way as a result of a very old decision before .aar's even existed).  Without furhter support for this scenario in Xamarin.Android itself, we'd basically have to manually extract .aar files, merge their contents (including merging things like proguard rules, androidmanifest.xml files, resources, etc) into one single .aar and then bind that.  This isn't a path we're going to take.  There is some support planned in Xamarin.Android for including .aar files from outside of .net .dll assemblies, but it's not implemented yet.  We basically need this as well before we can realistically combine these things.

**Comment by JohannesSchmidt42** [comment]
A non Xamarin Android App that has to support Android down to API 16, has Recycler Views, TextInputLayouts, VectorDrawables, Material Design and CardViews and PayPal SDK integration. 

A separate offering that combines all or at least most of the support libraries would help very much. 
Yes it should not substitute the separat packages live next to them so that you can choose between the full package or this mess: 

![image](https://user-images.githubusercontent.com/7668232/33852512-2b5e9a8a-debb-11e7-8cc5-0cdec0012606.png)

**Comment by newky2k** [comment]
We are changing the AndroidSupport libraries to reflect the changes google is making to them so there my be changes once they are released.
