### ISSUE TITLE
Xamarin.Android.Support.Constraint.Layout Problem in barrierDirection

### ISSUE THREAD

**Issue by johnjake** [xamarin/AndroidSupportComponents#80]
### Include any relevant Exception Stack traces, build logs, adb logs: Severity	Code	Description	Project	Project Rank	File	Line	Column	Category	Source	Suppression State	Tool
Error		No resource identifier found for attribute 'constraint_referenced_ids' in package 'com.cardviewrecycler.app'	CardViewRecyclerView	1	E:\GitProject\CardViewRecyclerView\CardViewRecyclerView\CardViewRecyclerView\Resources\layout\page_review.axml	2			Build		

Severity	Code	Description	Project	Project Rank	File	Line	Column	Category	Source	Suppression State	Tool
Error		No resource identifier found for attribute 'barrierDirection' in package 'com.cardviewrecycler.app'	CardViewRecyclerView	1	E:\GitProject\CardViewRecyclerView\CardViewRecyclerView\CardViewRecyclerView\Resources\layout\page_review.axml	2			Build

**Comment by Redth** [comment]
I'm not sure how to reproduce this.  Could you provide a solution which highlights the problem?  This sounds like it could be some other dependency expecting a resource that doesn't exist, but I'm not sure it's caused by cardview or recyclerview.  One other thing that comes to mind is that you should make sure the nuget package versions for these support libraries match.

**Comment by cyberjacob** [comment]
This appears to be caused by this version of ConstraintLayout not including support for a Barrier.
Any chance of getting this updated for `1.1.0-beta4`?

**Comment by Redth** [comment]
1.1.2 is out now which hopefully addresses this!
